#!/bin/bash

# Prompt user for prefix input
read -p "Enter prefix to prepend to file names (Press Enter for current date): " user_prefix

# Default prefix to current date if user input is empty
if [ -z "$user_prefix" ]; then
    prefix=$(date +'%Y-%m-%d')
else
    prefix="$user_prefix"
fi

path="/root/bashScripts/demoFolder/"
#use *.* for current directory


# Loop through all files in the current directory
for file in $path*
# here * iterates over all files in the directory specified by $path.

do
    # Check if the item is a file (not a directory)
    if [ -f "$file" ];
    then
        # Get the file name without the extension
        filename=$(basename "$file")
        
        #  Here, double # will remove everything from the beginning of the string up to the last dot.
        extension="${filename##*.}"
       	#  E.g : For file "example.tar.gz" sinlge # in ${filename#*.} will remove everything up to the first dot, leaving us with "tar.gz" 

       	
	# Check if the file has an extension
        if [ "$extension" != "$filename" ]
       	then
            
	    # Get the file name without extension
            filename="${filename%.*}"
        
	    # Include the dot only if the extension exists
	    new_filename="$prefix"_"$filename.$extension"
        
    	else
            # Set new filename without extension
            new_filename="$prefix"_"$filename"
        fi

        echo "Original file name: $file"
        echo "New file name: $new_filename"

        # Rename the file
        mv "$file" "$path$new_filename"
    fi
done

