#!/bin/bash

echo “Enter the file path”
read path

#identify the file type

if [ -d $path ]
then
	echo "This is a directory"
elif [ -f $path ]
then
	echo "This is a regular file"
else
	echo "This is other than regular file"
fi

echo "Listing the file"

ls -l $path
