#!/bin/bash

file="/etc/fstab"

#Check if file exists

if [ -e “$file” ]
  then
     echo “$file passwords are enabled”
fi

#check if file is executable
if [ -x “$file” ]
  then
    echo “You have permition to execute $file”
  else
    echo “You do Not have permissions to execute $file”
fi
