#!/bin/bash

# Check if any arguments are provided
if [ $# -eq 0 ]
then
    echo "Usage: $0 <file_or_directory1> [<file_or_directory2> ...]"
    echo "Enter argument(s) to run script"
    exit 1
fi

# Loop through each arguments

for path in "$@"
do
    if [ -d "$path" ]
    then
        echo "$path is a directory"

    elif [ -f "$path" ]
    then
        echo "$path is a regular file"

    else
        echo "$path is other than a regular file"
    fi

    echo "Listing $path"
    ls -l "$path"
    echo ""
done

# "$@" is used to represent all the file and directory names provided as arguments when running the script, and $# is used to check if any arguments are provided.
